# Generated by Django 2.1.7 on 2019-03-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Post date'),
        ),
    ]
