name: deploy

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@master

    - uses: actions/setup-python@v1

    - uses: dschep/install-pipenv-action@v1

    - name: Create requirements file
      run: pipenv lock --requirements > requirements.txt

    - name: Build
      run: docker build . --file Dockerfile --tag michaelpak/self

    - name: Push
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: michaelpak/self
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
