name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@master
    - name: Build
      run: docker build . --file Dockerfile --tag michaelpak/self
    - name: Push
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: michaelpak/self
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
